### ISSUE TITLE
Update Header font

### ISSUE THREAD

**Issue by tsongtheng** [tsongtheng/Social-Profiles#1]
Change the font of Header. Go to google-fonts and search for suitable font for the header.  Import it to `index.css`.  Don't remove the old-font import. Also, add suitable font-color and background-color  of the Header.

**Comment by ishan-nahid** [comment]
!assign

**Comment by tsongtheng** [comment]
You can also contribute by adding your social profiles links and make a pull request. For further details check `README.md`

**Comment by ishan-nahid** [comment]
check, review, feedback, marge.
