### ISSUE TITLE
Add Favicon

### ISSUE THREAD

**Issue by tsongtheng** [tsongtheng/Social-Profiles#2]
Add a new favicon. Remove the react default  favicon.

**Comment by Aneal07** [comment]
Assign me this, please.

**Comment by tsongtheng** [comment]
You can also contribute to this repository by adding your social media profile links and make a pull request. For further details, please checkout out the `README.md`.

**Comment by Aneal07** [comment]
What sort of image that you have in your mind for a new favicon?

**Comment by tsongtheng** [comment]
Anything related to social profiles.

**Comment by tsongtheng** [comment]
[Check this out](https://www.vectorstock.com/royalty-free-vector/social-logo-vector-21540596).

**Comment by tsongtheng** [comment]
Check out the link I have provided above. You can use one of those logos.

**Comment by Aneal07** [comment]
![social-media](https://github.com/tsongtheng/Add-Social-Profiles-Hacktoberfest2023/assets/120375605/b0cc55f4-73de-43f9-bf08-f942231e7dd8)
is this okay ?? you mentioned social media and  I thought this sort of image if not I can find out something else.

**Comment by tsongtheng** [comment]
Check this link: https://www.vectorstock.com/royalty-free-vector/social-logo-vector-21540596
